language: scala

scala:
- 2.11.12
- 2.12.8

jdk:
- oraclejdk8

branches:
  only:
  - master
  - 0.5.1

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.coursier


script: "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"